---
build_from:
  aarch64: ghcr.io/hassio-addons/ubuntu-base/aarch64:13.1.1
  amd64: ghcr.io/hassio-addons/ubuntu-base/amd64:13.1.1
  armhf: ghcr.io/hassio-addons/ubuntu-base/armhf:13.1.1
  armv7: ghcr.io/hassio-addons/ubuntu-base/armv7:13.1.1
  i386: ghcr.io/hassio-addons/ubuntu-base/i386:13.1.1
