---
name: TVHeadend
version: 2.4.6
stage: stable
slug: tvheadend
description: TV streaming server and recorder.
url: "https://github.com/mkenfenheuer/addon-tvheadend"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
#webui: "http://[HOST]:[PORT:9981]/"
ingress: true
ingress_port: 9981
devices:
  - /dev/dvb
  - /dev/dri
ports:
  9981/tcp: 9981
  9982/tcp: 9982
ports_description:
  9981/tcp: TVH Web Interface
  9982/tcp: TVH HTSP
map:
  - "config:rw"
options:
  system_packages: []
  init_commands: []
  additional_arguments: []
schema:
  system_packages:
    - str
  init_commands:
    - str
  additional_arguments:
    - str
